apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: image-name
      type: string
      description: "Container image reference to build and push"
      default: "us.icr.io/tax-calculator:latest"
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/syedmuhammadshah510/Tax-Calculator.git"
        - name: revision
          value: "main"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: npminstall
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: app-source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: app-source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: pipeline-workspace
